wireguard:
    private_key: ENC[AES256_GCM,data:L6FD+kBF7AoIrm3pMM6/pmWtX2FP5dUrJ9hUCuW9n4SlJ/JhpxI9m/1owIg=,iv:ok4pyUUv80kPY9n4WQmBGYHmMsPJnG0tnF+vbNhqc3s=,tag:OPribO7RoVCkFkTrYrHw7w==,type:str]
pi-hole:
    psk: ENC[AES256_GCM,data:t3FQ+SgU06ft9rZF0iC+J0S159id8U9Q4DU=,iv:RtPepopq8ndcqg2I4LOcqIdC+WIzcICeIb7+7fD+TYY=,tag:W5VxNF5fxC0hwG32sEV0Rw==,type:str]
    web_admin_password: ENC[AES256_GCM,data:w0YmyLapcPJ7wIyl8A==,iv:2BYdxZPtIX6zZkEaN3mOQgcImU0hegNgg04zkjAYGTQ=,tag:2fzWRD/T0xYgPyzsRCqmuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJamxiNDlnRWJ6ZGFRaEtu
            bGRveE9aWWY4c2duYkFYU2NKQlBSYjNWT3dZClNtNkpiRENNRFdUcTN6MENhU1Z1
            YzVDa21peTluVkFoQURnK0xZQjNFZm8KLS0tIGpPbE95NVM2aUNrWWlEVGUybXpP
            cXpCMmsxTkxKSXBjSmV2azNIcW04a1UKF8O99FpHDZSO0XFeCzWyoxJvjmvjvWFH
            aOFSWHO64UDlSY/1eQmIYr/xad/BxxYnkrqlJib5tpmPkoi1qyuZVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18gts35ruwj67kjgjtgrgrxup83apr8ekgrp98r434wcn2pf0l9sqnq5j2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmlDMzJQSEM3cjdnZmpy
            RUgzZTYvT3RrQ2RMUmNNNWRvL2NjSUJvdW1jCkFvaVFOZUdPMWQxNnhGLzgwa2w4
            MHpwVzJkQjZvd25oaENqbzdrT1dmazQKLS0tIE1MdmVrNVRscGlXeTB0NXV6SUMv
            RDNob1FNdFZQUUk0SmVDUnZBc3FNdVEKcyNWzjvIZIBR39kQkUsSSmHJ+gePPtbS
            PUcLp6jYFvPDyldLm+PqIApEL9X0d/0ccvY+wwkPCiqSPFZbBLitgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T09:42:37Z"
    mac: ENC[AES256_GCM,data:UU8lPnB4hllHjroJfCFKXs/+6bkknCml1my3Et9lDIdrZ/dGfM3VOS7vuRzZPY+3GA4kj+iphWL9ivbybnVhrTxK2DkE+Yk/xL6x4kWSZNAhhzPfHRFPXzhjBQPeuvX40DpmPkro2knQDqbU50XuzVYrEJVIBTYkc6YiB7GVFZs=,iv:g2x0WzrDYxaInWiT8F0a3+MvSTWIn1ftS1VdRS6UbwI=,tag:LN1R71pw7uK4hj9mfjAZxA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
