wireguard:
    private_key: ENC[AES256_GCM,data:L6FD+kBF7AoIrm3pMM6/pmWtX2FP5dUrJ9hUCuW9n4SlJ/JhpxI9m/1owIg=,iv:ok4pyUUv80kPY9n4WQmBGYHmMsPJnG0tnF+vbNhqc3s=,tag:OPribO7RoVCkFkTrYrHw7w==,type:str]
pi-hole:
    psk: ENC[AES256_GCM,data:t3FQ+SgU06ft9rZF0iC+J0S159id8U9Q4DU=,iv:RtPepopq8ndcqg2I4LOcqIdC+WIzcICeIb7+7fD+TYY=,tag:W5VxNF5fxC0hwG32sEV0Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJamxiNDlnRWJ6ZGFRaEtu
            bGRveE9aWWY4c2duYkFYU2NKQlBSYjNWT3dZClNtNkpiRENNRFdUcTN6MENhU1Z1
            YzVDa21peTluVkFoQURnK0xZQjNFZm8KLS0tIGpPbE95NVM2aUNrWWlEVGUybXpP
            cXpCMmsxTkxKSXBjSmV2azNIcW04a1UKF8O99FpHDZSO0XFeCzWyoxJvjmvjvWFH
            aOFSWHO64UDlSY/1eQmIYr/xad/BxxYnkrqlJib5tpmPkoi1qyuZVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18gts35ruwj67kjgjtgrgrxup83apr8ekgrp98r434wcn2pf0l9sqnq5j2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmlDMzJQSEM3cjdnZmpy
            RUgzZTYvT3RrQ2RMUmNNNWRvL2NjSUJvdW1jCkFvaVFOZUdPMWQxNnhGLzgwa2w4
            MHpwVzJkQjZvd25oaENqbzdrT1dmazQKLS0tIE1MdmVrNVRscGlXeTB0NXV6SUMv
            RDNob1FNdFZQUUk0SmVDUnZBc3FNdVEKcyNWzjvIZIBR39kQkUsSSmHJ+gePPtbS
            PUcLp6jYFvPDyldLm+PqIApEL9X0d/0ccvY+wwkPCiqSPFZbBLitgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T08:56:00Z"
    mac: ENC[AES256_GCM,data:ENbrH9OX9ZnlYW821lhnpaWZz8s+VZ5v933wXeJ+jaZjFq4RSiwW3t8IYaolZ0uiDI21OZ/r1MBBmKrAunAm3DQ2cwzbyDyIZ4r9zfmFESKJSzJAgK+whHswW9xGt7ZdQr30QQ8Naek9NnexJHqKj+trPdKP3tPoRwglg3n+ovU=,iv:mgsehl5f4N+Yqt/iV5njc0vX68uXcTzxvrB0VjKU7Hw=,tag:34muvEsAnxG0rNcEhRC+zw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
