caddy:
    ovh_endpoint: ENC[AES256_GCM,data:AhJ638eD,iv:wPyhaDuyNYfCobJXaTlZAjfrq62/2UcjLh87Hu/vRU4=,tag:rh34T9ty5g6Wa/VUTOgwvQ==,type:str]
    ovh_application_key: ENC[AES256_GCM,data:Ut+taYB64C4dtp1J1xz7AA==,iv:5EwYCCH5UW/Qks5GyCHQRXF/VJYq2tZUQJ0Qx4NkZ2E=,tag:Ohfr2fb1fXAMEsNoJ/0Tvg==,type:str]
    ovh_application_secret: ENC[AES256_GCM,data:X2pjBphoihkOIA7VA+SsaZQW73Sf7fIgqmLB9dNJei0=,iv:ttZwGeCKLTtPFqKkDqLG8w6D6y46i73Pcg9sFj8dTSM=,tag:d4qDOuJmW6CA9Sa6kqP/YA==,type:str]
    ovh_consumer_key: ENC[AES256_GCM,data:x3x4y1O+BiGpPJ+2r/sCTjUFzExvBRwPZreQzEm5edA=,iv:IVAdie95bnEF7Pi5r6F9GNdG0+NC2jDhBsWNbywbuLs=,tag:b79IE3lgBeaOp6EuzzdW7Q==,type:str]
garage:
    RPC_SECRET: ENC[AES256_GCM,data:+SEm07Y+hOWP0zNhIGuvkTxiJA2PheAndM4YaX5IpFSNCDT5Alb1M7sVJBf7ajTvgnEbkw4FXAQKDdsF+w0MUg==,iv:meS78fj60iQRnuHvmTR/QxOLFFAxc3w69BvMd2YBLQI=,tag:75xc9tyq+zh3J26wY/tpNQ==,type:str]
pi-hole:
    psk: ENC[AES256_GCM,data:t3FQ+SgU06ft9rZF0iC+J0S159id8U9Q4DU=,iv:RtPepopq8ndcqg2I4LOcqIdC+WIzcICeIb7+7fD+TYY=,tag:W5VxNF5fxC0hwG32sEV0Rw==,type:str]
    web_admin_password: ENC[AES256_GCM,data:w0YmyLapcPJ7wIyl8A==,iv:2BYdxZPtIX6zZkEaN3mOQgcImU0hegNgg04zkjAYGTQ=,tag:2fzWRD/T0xYgPyzsRCqmuQ==,type:str]
restic:
    user: ENC[AES256_GCM,data:LdjFeoV2,iv:Ktx/+m3A1w9sTaJC87ngiaxismusCAqIisNAHnu/ss8=,tag:VmStn6OthX1mMuCpEwWp+g==,type:str]
    password: ENC[AES256_GCM,data:4K1mWcM8zEu52MSbJLC5BQ1rd+BHtcAYaV6Y69B/HbvHia4oumxyVJtTLFO3ewkbMLJO5AOqXs18AebaoCHk8A==,iv:L/GNaqQs8eW6aub91BJkxdNrhIrtbJavkmcMYKobvBE=,tag:xskmjj8G8oVlLpyhyrEi2g==,type:str]
    htpasswd: ENC[AES256_GCM,data:z5pMMDiaNPbbaTU2iBLMlFd6Bjz/oQNwMSGN3RaPM7nO24WptCToFzEfQoHM6WHe3Lgxe7z/Wu8Q2t8/IfGFl4msFA==,iv:j2gMgU8F0kmnIzSHbsVpgZIB5JGhkU98Le0Dy5949zg=,tag:5DxSIJ18lS2DDLtnR0qSzw==,type:str]
webdav:
    GASPARD_PASSWORD: ENC[AES256_GCM,data:NrYFN11xqREVpu4=,iv:SwHvb/hSWZs15UgUrrs2MIpWq2FqTJPyMixh1yyIPR8=,tag:GXCOs41xelKofZs+lSZW9Q==,type:str]
    EMMA_PASSWORD: ENC[AES256_GCM,data:DqyzrVBCpNbgQYkW2DlmRerQ,iv:iikN0881nLYA9hwOUsiExL7zLOHGyboxyPod4KyJ24I=,tag:GXvzWCtUG8+/4qX2sfcUtg==,type:str]
wireguard:
    private_key: ENC[AES256_GCM,data:L6FD+kBF7AoIrm3pMM6/pmWtX2FP5dUrJ9hUCuW9n4SlJ/JhpxI9m/1owIg=,iv:ok4pyUUv80kPY9n4WQmBGYHmMsPJnG0tnF+vbNhqc3s=,tag:OPribO7RoVCkFkTrYrHw7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THdqVGN0L3NGMzMxdU91
            RmlkZFFpekRSVXdEWENkNDA0TURHbXRzVW5jCkViWjBRdXNTTnBHeTI0T2ZjVCt2
            TnYwN3MvY0VDSTdsazk2S2hIaGNaYTQKLS0tIHVLT1hZb0tGV01vMDZSakJ5ZGJL
            NzBDcUhneFlBdytHMHFDK0t2aXJWNFkKqSvYlUdq21M+YUJ+TegUUR36+atYCz2K
            l7q++0EfbB3U6NOaUvyGV9MgUGjzhlP5LcxVZ7Gc2r2rB2G+HBkIBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRkgweDhlR3JkVU1KUEUv
            YWJzSlBvY3o0cHlHb1BSU2xyaDlRcU1WYzJ3CjFBcXNxSkw2TC9CQlQ5MVY4ZFRz
            UllFSGNqaWNTcE9UdU1HeE9LbmQ0bGcKLS0tIFFBVEtDL1RCWE5vL0M2TG4zRHJt
            L3ZlVVJ2cnFmTUlKWXpDTHBRNG5qLzQKaJE0LPf+K87gsvz9EyfSRBII9IcnW2D3
            IyLsOtz0zLdW+TldAXvuvIZ5LJTx5DZ6o2gRKgTdvo3eGJoQ9lzxkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvlspzka8ge8qdj5s2tm0cu756txhd7gkvps5wu40qqwft7hjd9scl3jes
    lastmodified: "2026-02-23T14:41:11Z"
    mac: ENC[AES256_GCM,data:AwUlAwvFYfDjUsxycVTM553VGItE+HqPGxhUc4ehRt2lfTwzDZ+GnYmbb7fMJ2MxeZ+67I2KdGGPnz9MfRICsars4yEeax7bJ0O7YfwxFgzhluuAQdBmASe3AN3XIPNvVTGi+Si22iYsDoUmuLOXxF0TW1Lccvlrd8d9bXEapUk=,iv:EEVwUZNc0H5TzG5NPaNseBHQvnjids7NTc9njyJopWw=,tag:nOvexY6Hwb9R4jTr3hybvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
