wireguard:
    private_key: ENC[AES256_GCM,data:L6FD+kBF7AoIrm3pMM6/pmWtX2FP5dUrJ9hUCuW9n4SlJ/JhpxI9m/1owIg=,iv:ok4pyUUv80kPY9n4WQmBGYHmMsPJnG0tnF+vbNhqc3s=,tag:OPribO7RoVCkFkTrYrHw7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUXdiSUcrcEJsdUtQOVlB
            SEZMY1FIdzJOLzlKbGg3VWl6ZTh2KzVvMmdBCmVpRFNPcGd6cnI4eStFcVNXL2x1
            N0tiWGZJRlZ5NzA2TGJMQVprelpZT3cKLS0tIGJjaDhmZm5UanV2MVdjTTNjVWhs
            am9xKzBocEdRNWsyN2xzR2dEWitCcFUKCBll3AW0JxO3vs2QD3enVyCbqg8D1udR
            LMqByCmXz9iN5gv1//TvDofMa1om6fCVtMhsq/lin9DoQ5gZFQ9Kpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wwpxvvgtr03vplj5vca50fk48c5twpukyzg5q36xcq35pzdkpv5qx8x28t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMTZNdnZnUHN3eSs5eldD
            K3lPdmJrRnRYbFBoY0NPMVRwNjZqTS9xWkdVCjJGOU05aUIxU3RKL1U4T0tQd0tl
            SVltSWJKMVdvYXlJVTFMMEFreTF0dW8KLS0tIE04ZWI4UzhVS0Z1bVF0blY3UFBQ
            b2FrbzZtbnZtZTlJaFYwR2lQMjFwOHMKndUeR8P/ofi1slon7GfTX3sTihfgBAdR
            wmnDwQS2HpctlFtIm/+sRElHh7Dk8/VSVmYb7yqQCB5TnH8DiQddVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:30:48Z"
    mac: ENC[AES256_GCM,data:GI5Hb8zvafTdWhpm+D6qp9iefMD9NwYPRBKcxrIL9M1wTMzMzD4QsrbMDKQELfTYK3QhLZ0G4KTmLfoSB1zYO/GtslRDAAHmFzLuNNVJ9/8gIrd/Gb12JLnUDjJrxYEeF15NKnyqRMKUVQiJgYd8ggLGzT9pRqaMNTKCYutqsaE=,iv:XB/Ddi7mU9SdRD7nHkyAZR+gTZ9ZY2ZrvHlb0kFK/4Q=,tag:OgEw78w4o44CamP/4C6Y7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
