caddy:
    ovh_endpoint: ENC[AES256_GCM,data:AhJ638eD,iv:wPyhaDuyNYfCobJXaTlZAjfrq62/2UcjLh87Hu/vRU4=,tag:rh34T9ty5g6Wa/VUTOgwvQ==,type:str]
    ovh_application_key: ENC[AES256_GCM,data:Ut+taYB64C4dtp1J1xz7AA==,iv:5EwYCCH5UW/Qks5GyCHQRXF/VJYq2tZUQJ0Qx4NkZ2E=,tag:Ohfr2fb1fXAMEsNoJ/0Tvg==,type:str]
    ovh_application_secret: ENC[AES256_GCM,data:X2pjBphoihkOIA7VA+SsaZQW73Sf7fIgqmLB9dNJei0=,iv:ttZwGeCKLTtPFqKkDqLG8w6D6y46i73Pcg9sFj8dTSM=,tag:d4qDOuJmW6CA9Sa6kqP/YA==,type:str]
    ovh_consumer_key: ENC[AES256_GCM,data:x3x4y1O+BiGpPJ+2r/sCTjUFzExvBRwPZreQzEm5edA=,iv:IVAdie95bnEF7Pi5r6F9GNdG0+NC2jDhBsWNbywbuLs=,tag:b79IE3lgBeaOp6EuzzdW7Q==,type:str]
pi-hole:
    psk: ENC[AES256_GCM,data:t3FQ+SgU06ft9rZF0iC+J0S159id8U9Q4DU=,iv:RtPepopq8ndcqg2I4LOcqIdC+WIzcICeIb7+7fD+TYY=,tag:W5VxNF5fxC0hwG32sEV0Rw==,type:str]
    web_admin_password: ENC[AES256_GCM,data:w0YmyLapcPJ7wIyl8A==,iv:2BYdxZPtIX6zZkEaN3mOQgcImU0hegNgg04zkjAYGTQ=,tag:2fzWRD/T0xYgPyzsRCqmuQ==,type:str]
wireguard:
    private_key: ENC[AES256_GCM,data:L6FD+kBF7AoIrm3pMM6/pmWtX2FP5dUrJ9hUCuW9n4SlJ/JhpxI9m/1owIg=,iv:ok4pyUUv80kPY9n4WQmBGYHmMsPJnG0tnF+vbNhqc3s=,tag:OPribO7RoVCkFkTrYrHw7w==,type:str]
sops:
    age:
        - recipient: age1rgu2e75kt4uztr43y6wj70uz2sj3tr9lz58y4h6rk37alq2vwa5q9v35dr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJamxiNDlnRWJ6ZGFRaEtu
            bGRveE9aWWY4c2duYkFYU2NKQlBSYjNWT3dZClNtNkpiRENNRFdUcTN6MENhU1Z1
            YzVDa21peTluVkFoQURnK0xZQjNFZm8KLS0tIGpPbE95NVM2aUNrWWlEVGUybXpP
            cXpCMmsxTkxKSXBjSmV2azNIcW04a1UKF8O99FpHDZSO0XFeCzWyoxJvjmvjvWFH
            aOFSWHO64UDlSY/1eQmIYr/xad/BxxYnkrqlJib5tpmPkoi1qyuZVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18gts35ruwj67kjgjtgrgrxup83apr8ekgrp98r434wcn2pf0l9sqnq5j2y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQmlDMzJQSEM3cjdnZmpy
            RUgzZTYvT3RrQ2RMUmNNNWRvL2NjSUJvdW1jCkFvaVFOZUdPMWQxNnhGLzgwa2w4
            MHpwVzJkQjZvd25oaENqbzdrT1dmazQKLS0tIE1MdmVrNVRscGlXeTB0NXV6SUMv
            RDNob1FNdFZQUUk0SmVDUnZBc3FNdVEKcyNWzjvIZIBR39kQkUsSSmHJ+gePPtbS
            PUcLp6jYFvPDyldLm+PqIApEL9X0d/0ccvY+wwkPCiqSPFZbBLitgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T23:10:00Z"
    mac: ENC[AES256_GCM,data:1IHK4np7N5GQ25HIwWf2EmC+VRLk809KnI9wL+es1diEeXyPI1sH8VuEbOuH3nOxtnIT4hYYHn72y+86PaUke9fu8rHznhbBEX8Q8W9u9BQzYHIzXqHtI14JVVkDRSVyw88qwAWbYv5XtbS1JFE0EHSEbpxy7ty+nzyG61eAVTw=,iv:WaNHghmMdmQTj52p2jZ2c5z8+1Idd6BT4SlyVOfd4TY=,tag:vVN7xgqGPTf0fJ7Nf8jR0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
