#!/bin/bash

get-profile () {
  asusctl profile -p | awk '{print $4}'
}

active_profile="$(get-profile)"

if [ "$active_profile" == "Quiet" ]; then
  asusctl profile -P Balanced
elif [ "$active_profile" == "Balanced" ]; then
  asusctl profile -P Performance
else
  asusctl profile -P Quiet
fi

pkill -USR1 i3status-rs
