#!/usr/bin/env bash

refresh_rate=$(xrandr --screen 0 | grep "*" | cut -d "*" -f 1 | awk '{print $NF}' | cut -d "." -f 1)

if [ $button ]; then
	if [ $refresh_rate == "60" ]; then
		xrandr --screen 0 -r 165
		echo "165Hz"
	else
		xrandr --screen 0 -r 60
		echo "60Hz"
	fi
else
	echo "${refresh_rate}Hz"
fi
