{flake, ...}: let
  inherit (flake) inputs;
  inherit (inputs) self;
in {
  imports = [
    self.homeModules.default
  ];

  home.username = "gaspard";
  home.homeDirectory = "/home/gaspard";

  programs.home-manager.enable = true;
  programs.direnv.enable = true;

  gasdev = {
    shell = {
      bash.enable = true;
      helix.enable = true;
      zellij.enable = true;
    };
  };

  programs.git = {
    enable = true;
    settings = {
      user = {
        name = "GaspardCulis";
        email = "gaspard@gasdev.fr";
        init.defaultBranch = "main";
      };
    };
  };

  services = {
    ssh-agent.enable = true;
  };

  home.file.".ssh/authorized_keys_link" = {
    text = ''
      # This file was auto-generated by home-manager, any changes will be overwritten during the next reswitch.
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQyRXFQ6iA5p0vDuoGSHZfajiVZPAGIyqhTziM7QgBV gaspard@nixos
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICm9trfkWL5FVHuo/5YONd+oZY4nQnpHLDOnXoOrl9j9 u0_a220@pixel
    '';
    onChange = ''
      cat ~/.ssh/authorized_keys_link > ~/.ssh/authorized_keys
      rm ~/.ssh/authorized_keys_link
      chmod 600 ~/.ssh/authorized_keys
    '';
    force = true;
  };

  home.sessionPath = [
    "$HOME/.local/bin"
  ];
}
