#!/bin/dash

spaces (){
	hyprctl workspaces -j | jq -c 'map({id: .id, windows: .windows, monitor: .monitorID})'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done

