{
  pkgs,
  enableDesktop ? false,
  ...
}: let
  lib = pkgs.lib;
in {
  home.username = "gaspard";
  home.homeDirectory = "/home/gaspard";
  home.stateVersion = "24.05";

  imports = [
    ../utils/allowed-unfree.nix
  ];

  programs.home-manager.enable = true;
  programs.direnv.enable = true;

  gasdev = {
    shell = {
      bash.enable = true;
      helix.enable = true;
      zellij.enable = true;
    };
    desktop = lib.mkIf enableDesktop {
      enable = true;
      niri = {
        enable = true;
        autoStart = true;
        xwayland.enable = true;
      };
      apps = lib.mkIf enableDesktop {
        software-center.enable = true;
        firefox = {
          progressiveWebApps.enable = true;
          profiles.gaspard.enable = true;
        };
      };
      udiskr.enable = true;
    };
  };

  services = {
    ssh-agent.enable = true;
  };

  home.file.".ssh/authorized_keys_link" = {
    text = ''
      # This file was auto-generated by home-manager, any changes will be overwritten during the next reswitch.
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQyRXFQ6iA5p0vDuoGSHZfajiVZPAGIyqhTziM7QgBV gaspard@nixos
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICm9trfkWL5FVHuo/5YONd+oZY4nQnpHLDOnXoOrl9j9 u0_a220@pixel
    '';
    onChange = ''
      cat ~/.ssh/authorized_keys_link > ~/.ssh/authorized_keys
      rm ~/.ssh/authorized_keys_link
      chmod 600 ~/.ssh/authorized_keys
    '';
    force = true;
  };

  stylix = {
    enable = true;
    icons = {
      enable = true;
      package = pkgs.colloid-icon-theme;
      dark = "Colloid-Dark";
      light = "Colloid-Light";
    };
  };

  xdg.mimeApps = lib.mkIf enableDesktop {
    enable = true;
    defaultApplications = {
      "text/html" = "firefox.desktop";
      "application/pdf" = "firefox.desktop";
      "x-scheme-handler/http" = "firefox.desktop";
      "x-scheme-handler/https" = "firefox.desktop";
      "x-scheme-handler/about" = "firefox.desktop";
      "x-scheme-handler/unknown" = "firefox.desktop";
    };
  };
}
