theme="sonokai"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[keys.normal]
backspace = {r = ":sh cargo run", p = ":sh python src/main.py"}
a = ["ensure_selections_forward", "collapse_selection", "move_char_right", "insert_mode"]
A-R = [":clipboard-paste-replace"]
