theme="sonokai"

[editor]
line-number = "relative"
mouse = false
preview-completion-insert = false
color-modes = true
cursorline = true

[editor.indent-guides]
render = true
character = "┆"

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
backspace = {r = ":sh cargo run", p = ":sh python src/main.py"}
a = ["ensure_selections_forward", "collapse_selection", "move_char_right", "insert_mode"]
A-R = [":clipboard-paste-replace"]
