[[language]]
name = "rust"

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = false

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "Poetry.lock", ".git"]
# language-servers = [{ command = "pyright-langserver", args = ["--stdio"] }]
auto-format = true
formatter = {command = 'black', args = ["--quiet", "-"]}

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/home/gaspard/.local/share/fnm/node-versions/v20.11.1/installation/lib/node_modules/typescript/lib"}, environment = "node"}
timeout = 2

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]

[language-server.spyglass]
command="spyglassmc-language-server"

[[language]]
name = "mcfunction"
scope = "source.mcfunction"
file-types = [ "mcfunction" ]
roots = [ "spyglass.json", ".spyglassrc.json" ]
language-servers = [ "spyglass" ]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--stdin-filepath", "dummy.scss"] }
indent = { tab-width = 4, unit = "\t" }
language-servers = ["vscode-css-language-server"]
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "hcl"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true
